load logic.maude

rew LOGIC : program(
block 'main start
    v('X)
    lbl('X2)
    lbl('X1)
    branch
end

block 'X1 start
    dup
    int(1)
    unif

    lbl('Gt0)
    lbl('Lt0)
    branch
end

block 'X2 start
    dup
    int(0)
    unif

    lbl('Gt0)
    lbl('Lt0)
    branch
end

block 'Gt0 start
    int(3)
    unif
end

block 'Lt0 start
    int(0)
    unif
end
) .

rew LOGIC : program(
block 'main start
    functor('empty, 0)
    int(1)
    functor('cons, 2)
    v('X)
    unif

    functor('empty, 0)
    v('Y)
    unif

    v('X)
    v('Y)
    unif
end) .

